name: challenge_uex
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cherry_toast: ^1.11.0
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  flutter_mobx: ^2.2.1+1
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  google_maps_flutter: ^2.7.0
  go_router: ^14.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mask: ^1.0.5
  mobx: ^2.3.3+2
  responsive_framework: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/icons/